### ISSUE TITLE
Utilisation de JUNIT 4

### ISSUE THREAD

**Issue by gronono** [gbertherat/Schotten-Totten#11]
https://github.com/gbertherat/Schotten-Totten/blob/bc9b5527c19cf9fd158e257defbfefbe40154769/pom.xml#L53

JUnit 4 a été remplacé par JUnit 5 dont le nom de code est Jupiter : https://junit.org/junit5/docs/current/user-guide/

Il est déjà inclus via la dépendance spring-boot-starter-test.

**Comment by gbertherat** [comment]
Merci pour l'info!
